language: csharp
mono: alpha
dotnet: 2.1.4
yarn: 1.3.2

os:
  - osx
  - linux

before_script:
 - chmod +x ./build.sh

script:
  - ./build.sh CIBuild BuildNumber=$TRAVIS_BUILD_NUMBER PullRequest=TRAVIS_PULL_REQUEST Branch=TRAVIS_BRANCH
